{% set name = "jupyterlab-h5web" %}
{% set version = "7.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_h5web-{{ version }}.tar.gz
  sha256: f9881cc13826161ebc979fdc8070f71bc2d39666ebbd47bf17d5eaa6ed3fe5a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter_packaging
    - pip
    - python >=3.6
  run:
    - h5grove =1.3.0
    - h5py >=3.5
    - jupyter_server >=1.6,<2
    - python >=3.6
    - ipython

test:
  imports:
    - jupyterlab_h5web
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/silx-kit/jupyterlab-h5web
  summary: A JupyterLab extension to explore and visualize HDF5 file contents.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - srmnitc
    - t20100
