{% set name = "jupyterlab-h5web" %}
{% set version = "12.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_h5web-{{ version }}.tar.gz
  sha256: e7d69a06634ce387521251176b977dd158e601ab11ca9eb990ad0b7b5b87ab8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling >=1.5.0
    - hatch-jupyter-builder
    - jupyterlab =4.4.6
    - hatch-nodejs-version >=0.3.2
    - pip
    - python {{ python_min }}
  run:
    - jupyter_server >=2.4.0,<3
    - h5grove =2.3.0
    - h5py >=3.5
    - python >={{ python_min }}
    - ipython

test:
  imports:
    - jupyterlab_h5web
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/silx-kit/jupyterlab-h5web
  summary: A JupyterLab extension to explore and visualize HDF5 file contents.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - srmnitc
    - t20100
