{% set name = "jupyterlab-h5web" %}
{% set version = "11.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_h5web-{{ version }}.tar.gz
  sha256: a813f8d717322b5b80ea85355ca620f33dfbb8375ce04db276524a5c61d22a6e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter_packaging
    - jupyterlab >=4,<5
    - pip
    - python >=3.8
  run:
    - h5grove =1.3.0
    - h5py >=3.5
    - jupyter_server >=1.6,<3
    - python >=3.8
    - ipython

test:
  imports:
    - jupyterlab_h5web
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/silx-kit/jupyterlab-h5web
  summary: A JupyterLab extension to explore and visualize HDF5 file contents.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - srmnitc
    - t20100
