{% set name = "jupyterlab-h5web" %}
{% set version = "12.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_h5web-{{ version }}.tar.gz
  sha256: c2616cdccb3ae7e82df1bb85d0e365b015e6a770625bfec059186b3a08fc85aa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter_packaging
    - jupyterlab >=4,<5
    - pip
    - python >=3.8
  run:
    - h5grove =2.2.0
    - h5py >=3.5
    - jupyter_server >=1.6,<3
    - python >=3.8
    - ipython

test:
  imports:
    - jupyterlab_h5web
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/silx-kit/jupyterlab-h5web
  summary: A JupyterLab extension to explore and visualize HDF5 file contents.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - srmnitc
    - t20100
