{% set name = "jupyterlab-h5web" %}
{% set version = "8.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_h5web-{{ version }}.tar.gz
  sha256: 784c6cafff088725cbc73fef8d6181bb690a1fc414868f74be9a3f57557b16b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter_packaging <2
    - jupyterlab >=3.1,<4
    - pip
    - python >=3.7
  run:
    - h5grove =1.3.0
    - h5py >=3.5
    - jupyter_server >=1.6,<3
    - python >=3.7
    - ipython

test:
  imports:
    - jupyterlab_h5web

about:
  home: https://github.com/silx-kit/jupyterlab-h5web
  summary: A JupyterLab extension to explore and visualize HDF5 file contents.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - srmnitc
    - t20100
